chatbot/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "chatbot"

urlpatterns = [
    path("", views.chat_view, name="chat_view"),
]

team/urls.py
from django.urls import path
from . import views

# from .views import MessageListCreateAPIView

app_name = "team"
urlpatterns = [
    # 마이팀 누르면 팀생성하기 또는 팀 가입하기 보여주기
    path("myteam/", views.myteam, name="myteam"),
    path("myteam/<int:team_id>/", views.myteam, name="team_dashboard"),
    # 팀 생성하기
    path("create_team/", views.create_team, name="create_team"),
    # 팀프로필 수정
    path(
        "update_team_profile/<int:pk>/",
        views.update_team_profile,
        name="update_team_profile",
    ),
    # 팀 가입하기 누르면 팀들 나오고 가입하기까지
    path("team_list/", views.team_list, name="team_list"),
    # 마이 팀페이지
    # path("team_dashboard/<int:team_id>/", views.team_dashboard, name="team_dashboard"),
    path("join_team/<int:team_id>/", views.join_team, name="join_team"),
    path("matches/", views.match_list, name="match_list"),
    path("matches/create/", views.create_match, name="create_match"),
    path("matches/join/<int:match_id>/", views.join_match, name="join_match"),
    path(
        "match_report/<int:team_id>/",
        views.create_match_result,
        name="match_report",
    ),
    path(
        "match_report_edit/<int:result_id>/",
        views.edit_match_result,
        name="match_report_edit",
    ),
    path("match_schedule/", views.match_schedule, name="match_schedule"),
    path("team_story/", views.team_story, name="team_story"),
    # path("chat/<int:team_id>/", views.team_chat, name="team_chat"),
    # path(
    #     "api/messages/<int:team_id>/",
    #     MessageListCreateAPIView.as_view(),
    #     name="message-list-create",
    # ),
    path("video_analysis/<int:team_id>", views.video_analysis, name="video_analysis"),
    path("leave_team/", views.leave_team, name="leave_team"),
    path("delete_team/", views.delete_team, name="delete_team"),
    # 게시판 리스트 url
    path("board/<int:team_id>/", views.board_list, name="board_list"),
    path("board/<int:team_id>/create/", views.board_create, name="board_create"),
    path("board/<int:team_id>/<int:pk>/", views.board_detail, name="board_detail"),
    path(
        "board/<int:team_id>/<int:pk>/update/", views.board_update, name="board_update"
    ),
    path(
        "board/<int:team_id>/<int:pk>/delete/", views.board_delete, name="board_delete"
    ),
    path(
        "board/<int:team_id>/<int:pk>/comment_delete/",
        views.board_comment_delete,
        name="board_comment_delete",
    ),
    path(
        "board/<int:team_id>/<int:pk>/comment_update/",
        views.board_comment_update,
        name="board_comment_update",
    ),
]

core/templates/base.html
{% load component_tags static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Football Agora</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/5.3.3/css/bootstrap.min.css' %}"/>
    <link href='https://unpkg.com/fullcalendar@5.3.1/main.min.css' rel='stylesheet' />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Comic+Neue:wght@400;700&family=Noto+Sans+KR:wght@400;700&display=swap" rel="stylesheet">

    <style>

    {#<script src='https://unpkg.com/fullcalendar@5.3.1/main.min.js'></script>#}
    {#<style>#}
        .cute-font {
            font-family: 'Comic Neue', 'Noto Sans KR', sans-serif !important;
        }

        .nav-pills {
            display: flex;
            justify-content: center;
            width: 100%;
        }
        .nav-pills .nav-item {
            flex: 1;
            text-align: center;
        }
        .nav-pills .nav-link {
            color: black;
            font-size: 1.5rem; /* 글자 크기 조정 */
            font-family: inherit; /* 부모 요소의 글씨체 상속 */
        }
        .nav-pills .nav-link:hover {
            color: black;
        }

        .navbar-item {
            position: relative;
            padding: 10px;
            display: flex;
            align-items: center; /* 높이 맞추기 */
        }

        .navbar-item .dropdown-menu {
            display: none;
            position: absolute;
            top: 40px;
            left: 0;
            background-color: white;
            box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
            z-index: 1;
        }

        .navbar-item:hover .dropdown-menu {
            display: block;
        }

        .dropdown-menu a {
            display: block;
            padding: 10px;
            color: black !important;
            text-decoration: none;
            white-space: nowrap;
        }

        .dropdown-menu a:hover {
            background-color: #f0f0f0;
            color: black !important;
        }

        .dropdown-toggle::after {
            display: none;
        }

        .profile-container {
            display: flex;
            align-items: center;
            position: relative;
        }

        .profile-container span {
            margin-right: 10px; /* 사용자 이름과 이미지 사이에 여백 추가 */
        }

        .profile-container img {
            margin-left: 5px;
            cursor: pointer;
        }

        .profile-buttons {
            display: flex;
            align-items: center;
        }

        .profile-buttons a {
            margin-left: 10px; /* 버튼들 사이에 여백 추가 */
        }

        .list-group-item {
            border: 1px solid #ddd;
            border-radius: 0.25rem;
            margin-bottom: 10px;
            transition: background-color 0.2s ease-in-out;
        }

        .list-group-item:hover {
            background-color: #f8f9fa;
        }

        .list-group-item .fa-2x {
            color: #007bff;
        }

        .card-header {
            background-color: #f8f9fa;
        }

        .card-header .btn-close {
            font-size: 1.25rem;
            padding: 0.5rem;
            cursor: pointer;
        }

        .card-footer .btn-warning {
            background-color: #ffc107;
            border-color: #ffc107;
        }

        .card-footer .btn-warning:hover {
            background-color: #e0a800;
            border-color: #d39e00;
        }

        .banner {
            position: relative;
            text-align: center;
            color: white;
        }

        .banner img {
            width: 100%;
            height: 400px;
        }

        .banner .slogan {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 2rem;
            background-color: rgba(0, 0, 0, 0.5);
            padding: 10px 20px;
            border-radius: 5px;
        }

        /* 검정색 상단 바 길이 조정 */
        header.p-3.text-bg-dark {
            height: 100px; /* 바 높이를 늘립니다. 필요에 따라 높이를 조정하세요 */
            display: flex;
            align-items: center;
        }

        /* 상단 바 안의 글씨 크기 조정 */
        header.p-3.text-bg-dark a,
        header.p-3.text-bg-dark .profile-container span,
        header.p-3.text-bg-dark .profile-buttons a {
            font-size: 20px; /* 글씨 크기를 늘립니다. 필요에 따라 크기를 조정하세요 */
            color: snow; /* 글씨 색상을 흰색으로 유지합니다 */
        }

    </style>
    {% component_css_dependencies %}
</head>
<body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}' class="cute-font">

<header class="p-3 text-bg-dark">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-between">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                FootballAgora
            </a>

            <div class="text-end">
                {% if not user.is_authenticated %}
                    {% url 'accounts:login' as login_url %}
                    <a href="{{ login_url }}{% if login_url != request.path %}?next={{ request.path }}{% endif %}" class="btn btn-outline-light me-2">로그인</a>
                    <a href="{% url 'accounts:signup' %}?next={{ request.path }}" class="btn btn-warning">회원가입</a>
                {% else %}
                    <div class="profile-container">
                        <span>{{ user.username }}님</span>
                        <div class="dropdown">
                            <img src="{% static 'images/soccer_ball.png' %}" alt="Profile" width="30" height="30" class="dropdown-toggle" id="profileDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                            <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                                <li><a href="{% url 'accounts:mypage' %}" class="dropdown-item">My Page</a></li>
                                <li><a href="{% url 'team:myteam' %}" class="dropdown-item">My Team</a></li>
                            </ul>
                        </div>
                        <div class="profile-buttons">
                            <a hx-post="{% url 'accounts:logout' %}?next={% url 'accounts:main' %}" hx-target="body" hx-push-url="true" class="btn btn-warning">로그아웃</a>
                            <a href="{% url 'accounts:password_change' %}" class="btn btn-warning">비밀번호 변경</a>
                        </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</header>



<main class="py-5">
    <div class="container">
        <header class="d-flex justify-content-center py-3">
            <ul class="nav nav-pills">
{#                <li class="nav-item navbar-item"><a href="#" class="nav-link" aria-current="page">풋살장 예약</a></li>#}
                <li class="nav-item navbar-item">
                    <a href="#" class="nav-link">FA TEAM</a>
                    <div class="dropdown-menu">
                        <a href="{% url 'team:team_story' %}">Team Story</a>
                        <a href="{% url 'team:match_list' %}">Team Match</a>
                        <a href="{% url 'team:myteam' %}">My Team</a>
                    </div>
                </li>
                <li class="nav-item navbar-item"><a href="{% url 'chatbot:chat_view' %}" class="nav-link">Chatbot</a></li>
            </ul>
        </header>
         {% block banner %}{% endblock %}
        {% block content %}{% endblock %}
    </div>
</main>

<footer class="text-body-secondary py-5">
    <div class="container">
    </div>
</footer>
{% if debug %}
    <script src="{% static 'htmx/1.9.11/htmx.js' %}"></script>
{% else %}
    <script src="{% static 'htmx/1.9.11/htmx.min.js' %}"></script>
{% endif %}
<script src="{% static 'bootstrap/5.3.3/js/bootstrap.bundle.min.js' %}"></script>
{% component_js_dependencies %}
<script src="{% static 'htmx/ext/ hx-get-with-timestamp.js' %}"></script>
<script src="{% static 'toast-messages.js' %}"></script>

{% include "_messages_as_event.html" %}

</body>
</html>